# **NUMPY**

class name of numpy is ndarray.

Numpy is a python library used for working with arrays.

In python we have lists that serves the purpose of arrays, but they are slow to process.

Numpy aims to provide an array object that is upto 50* faster than traditional python lists.

The array object in numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science , where speed and resources are very important.

Collection of homogenous data.

Size is fixed.

numpy is a.


In [ ]:
import numpy as np

In [ ]:
import numpy as np

x = np.ndarray([2,3,6,1])

print(x)

[[[[1.        ]
   [1.        ]
   [0.8       ]
   [1.        ]
   [1.        ]
   [0.92941176]]

  [[0.62745098]
   [1.        ]
   [0.99607843]
   [0.85098039]
   [0.4627451 ]
   [1.        ]]

  [[0.99607843]
   [0.69803922]
   [0.29803922]
   [1.        ]
   [0.99215686]
   [0.55294118]]]


 [[[0.23529412]
   [1.        ]
   [0.98823529]
   [0.30588235]
   [0.16470588]
   [1.        ]]

  [[0.89019608]
   [0.10196078]
   [0.10980392]
   [1.        ]
   [0.74117647]
   [0.        ]]

  [[0.14901961]
   [1.        ]
   [0.50196078]
   [0.        ]
   [0.14901961]
   [1.        ]]]]


In [ ]:
import numpy as np

x = np.array([1,3,4,6])
print(x)

[1 3 4 6]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.ndim)

1


In [ ]:
print(x.shape)

(4,)


In [ ]:
import numpy as np

x = np.array([[1,2,3,4],[8,5,6,7]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4]
 [8 5 6 7]]
(2, 4)
2


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,55],[5,6,7,8,56],[9,10,11,12,57],[13,14,15,16,23]])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4 55]
 [ 5  6  7  8 56]
 [ 9 10 11 12 57]
 [13 14 15 16 23]]
(4, 5)
2


In [ ]:
import numpy as np

b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
2


In [ ]:
#1D - single axis - x
#2D - Two axis - x,y
#3D - Three axis - x,y,z

In [ ]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [ ]:
import numpy as np

array_1 = np.array([[[1,2],[3,4],[5,6],[7,8]],[[11,12],[13,14],[15,16],[17,18]]])

array_2 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[66,34,67]],[[22,68,90],[34,94,27]]])

array_3 = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]],
                    [[11,12],[34,28]],
                    [[67,45],[34,78]]])

print(array_1)
print(array_1.shape)
print(array_1.ndim)
print(array_2)
print(array_2.shape)
print(array_2.ndim)
print(array_3)
print(array_3.shape)
print(array_3.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]]]
(2, 4, 2)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [66 34 67]]

 [[22 68 90]
  [34 94 27]]]
(3, 2, 3)
3
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 12]
  [34 28]]

 [[67 45]
  [34 78]]]
(4, 2, 2)
3


In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,4),dtype = int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4),dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.arange(20,80,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [ ]:
np.linspace(20,80,8)

array([20.        , 28.57142857, 37.14285714, 45.71428571, 54.28571429,
       62.85714286, 71.42857143, 80.        ])

In [ ]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [ ]:
np.full((3,4),70,dtype = float)

array([[70., 70., 70., 70.],
       [70., 70., 70., 70.],
       [70., 70., 70., 70.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((2,3,2))

array([[[0.13497526, 0.36632257],
        [0.56633883, 0.37515425],
        [0.88467651, 0.58751595]],

       [[0.34097215, 0.62510303],
        [0.21278089, 0.16020593],
        [0.53939592, 0.82780945]]])

In [ ]:
np.random.randint(100,200,(3,2,2))

array([[[185, 104],
        [103, 125]],

       [[162, 117],
        [110, 101]],

       [[135, 119],
        [166, 190]]])

In [ ]:
np.random.randint(100,size=(3,2,3))

array([[[58, 24, 13],
        [91, 26,  2]],

       [[63, 85, 39],
        [47, 81, 15]],

       [[ 2, 83, 69],
        [94, 89, 97]]])

In [ ]:
a = np.array([[10,23,11],[5,7,8]])

b= np.array([[9,11,22],[12,33,67]])

print(a)
print(b)

[[10 23 11]
 [ 5  7  8]]
[[ 9 11 22]
 [12 33 67]]


In [ ]:
# ADD

np.add(a,b)

array([[19, 34, 33],
       [17, 40, 75]])

In [ ]:
# SUBTRACT

np.subtract(a,b)

array([[  1,  12, -11],
       [ -7, -26, -59]])

In [ ]:
# MULTIPLY

np.multiply(a,b)

array([[ 90, 253, 242],
       [ 60, 231, 536]])

In [ ]:
# DIVIDE

np.divide(a,b)

array([[1.11111111, 2.09090909, 0.5       ],
       [0.41666667, 0.21212121, 0.11940299]])

In [ ]:
# POWER

np.power(a,b)

array([[          1000000000,      952809757913927, -2732210440490168087],
       [           244140625,  5883222197588761863,                    0]])

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5],[1.2,5.6,2.6,8.6,9.2]])
print(a)
print(a.shape)
y = np.floor(a)

print(y)

[[1.  2.  3.  4.  5. ]
 [1.2 5.6 2.6 8.6 9.2]]
(2, 5)
[[1. 2. 3. 4. 5.]
 [1. 5. 2. 8. 9.]]


In [ ]:
b = np.array([[2,6,8,5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(b.shape)
x = np.ceil(b)
print(x)

[[2.  6.  8.  5.  4. ]
 [5.6 2.6 8.9 2.3 9. ]]
(2, 5)
[[2. 6. 8. 5. 4.]
 [6. 3. 9. 3. 9.]]


In [ ]:
b = np.array([[2,6,8,5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(b.shape)
x = np.round(b)
print(x)

[[2.  6.  8.  5.  4. ]
 [5.6 2.6 8.9 2.3 9. ]]
(2, 5)
[[2. 6. 8. 5. 4.]
 [6. 3. 9. 2. 9.]]


In [ ]:
b = np.array([[2,6,8,5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(b.shape)
x = np.rint(b)
print(x)

[[2.  6.  8.  5.  4. ]
 [5.6 2.6 8.9 2.3 9. ]]
(2, 5)
[[2. 6. 8. 5. 4.]
 [6. 3. 9. 2. 9.]]


In [ ]:
b = np.array([[2,6,8,5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(type(b))

[[2.  6.  8.  5.  4. ]
 [5.6 2.6 8.9 2.3 9. ]]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[2,6,8,5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(b.dtype)

[[2.  6.  8.  5.  4. ]
 [5.6 2.6 8.9 2.3 9. ]]
float64


In [ ]:
b = np.array([[2,6,'8',5,4],[5.6,2.6,8.9,2.3,9.0]])
print(b)
print(b.dtype)

[['2' '6' '8' '5' '4']
 ['5.6' '2.6' '8.9' '2.3' '9.0']]
<U32


In [ ]:
b = np.array([[2,6,'8',5,4],[5.6,2.6,8.9,2.3,9.0]])
x = b.astype(float)
print(x.dtype)

float64


In [ ]:
b = np.array([[2,6,'8',5,4],[5.6,2.6,8.9,2.3,9.0]])
x = b.astype(complex)
print(x.dtype)

complex128


**1 DIMENSIONAL SUBSETTING**

In [ ]:
import numpy as np
a = np.array([3,5,7,'6',1,9])
print(a[3])

6


**2 DIMENSIONAL SUBSETTING**

In [ ]:
import numpy as np
a = np.array([[3,5,7,'6',1,9],[3,5,6,'4',9,10]])
print(a[1,5])

10


In [ ]:
import numpy as np
a = np.array([[3,5,7,'6',1,9],[3,5,6,'4',9,10]])
print(a[0,3])

6


In [ ]:
import numpy as np
a = np.array([[3,5,7,'6',1,9],[3,5,6,'4',9,10]])
print(a[0,5])

9


**3 DIMENTIONAL SUBSETTING**

In [ ]:
import numpy as np
d = np.array([[[1,2,3,4],[5,6,7,8]],[[55,78,90,33],[11,22,44,55]]])
print(d[0,1,2])

7


In [ ]:
import numpy as np
d = np.array([[[1,2,3,4],[5,6,7,8]],[[55,78,90,33],[11,22,44,55]]])
print(d[1,0,3])

33


In [ ]:
import numpy as np
d = np.array([[[1,2,3,4],[5,6,7,8]],[[55,78,90,33],[11,22,44,55]]])
print(d[1,1,2])

44


**1D SLICING**

In [ ]:
import numpy as np
s = np.array([1,2,3,'5',6,7,8])
print(s[1:4])

['2' '3' '5']


In [ ]:
import numpy as np
s = np.array([1,2,3,'5',6,7,8])
print(s[1:])

['2' '3' '5' '6' '7' '8']


In [ ]:
import numpy as np
s = np.array([1,2,3,'5',6,7,8])
print(s[:5])

['1' '2' '3' '5' '6']


In [ ]:
import numpy as np
s = np.array([1,2,3,'5',6,7,8])
print(s[0:6])

['1' '2' '3' '5' '6' '7']


**2D SLICING**

In [ ]:
import numpy as np
s = np.array([[1,2,3,'5',6],[7,5,3,'4',9]])

print(s.ndim)

print(s[0:2,2:5])   #0th and 1st row and 2nd 3rd 4th columns
print(s[:,1:3])     #0th and 1st row and 1st and 2nd columns

2
[['3' '5' '6']
 ['3' '4' '9']]
[['2' '3']
 ['5' '3']]


**3D SLICING**

In [ ]:
import numpy as np
x = np.array([[[122,467,'567',738,678],[456,234,'432',789,908]],[[627,638,'638',809,253],[323,789,'254',232,890]]])
print(x.ndim)

print(x[:,1,2:6])

3
[['432' '789' '908']
 ['254' '232' '890']]


In [ ]:
import numpy as np
x = np.array([[[122,467,'567',738,678],[456,234,'432',789,908]],[[627,638,'638',809,253],[323,789,'254',232,890]]])
print(x.ndim)

print(x[:,:,1:4])

3
[[['467' '567' '738']
  ['234' '432' '789']]

 [['638' '638' '809']
  ['789' '254' '232']]]


**BOOLEAN INDEXING**

In [ ]:
import numpy as np
x = np.array([[[12,47,'567',738,678],[456,234,'43',789,98]],[[627,638,'638',809,253],[323,78,'254',232,80]]],dtype = int)
print(x)

[[[ 12  47 567 738 678]
  [456 234  43 789  98]]

 [[627 638 638 809 253]
  [323  78 254 232  80]]]


In [ ]:
a = x < 100
print(a)

[[[ True  True False False False]
  [False False  True False  True]]

 [[False False False False False]
  [False  True False False  True]]]


In [ ]:
b = x > 100

print(b)

[[[False False  True  True  True]
  [ True  True False  True False]]

 [[ True  True  True  True  True]
  [ True False  True  True False]]]


**FANCY INDEXING**

In [ ]:
import numpy as np
b = np.array([[[122,467,'567',738,678],[456,234,'432',789,908]],[[627,638,'638',809,253],[323,789,'254',232,890]]],dtype = int)

print(b[0,0,3])

738


In [ ]:
import numpy as np
b = np.array([[[122,467,'567',738,678],[456,234,'432',789,908]],[[627,638,'638',809,253],[323,789,'254',232,890]]],dtype = int)

print(b[[0],[1],[3]])

[789]


In [ ]:
import numpy as np
b = np.array([[[122,467,'567',738,678],[456,234,'432',789,908]],[[627,638,'638',809,253],[323,789,'254',232,890]]],dtype = int)

print(b[[0,1,1],[0,1,0],[3,1,2]])

[738 789 638]


**SORTING**

In [ ]:
import numpy as np

x = np.array([2,6,90,1,4,8])

y = np.sort(x)
print(y)

[ 1  2  4  6  8 90]


In [ ]:
import numpy as np

x = np.array([2,6,90,1,4,8])

y = np.sort(x)[::-1]
print(y)

[90  8  6  4  2  1]


In [ ]:
import numpy as np

x = np.array([[2,6,90,1,4,8],[56,2,11,67,90,22]])

x.sort()
print(x)

[[ 1  2  4  6  8 90]
 [ 2 11 22 56 67 90]]


In [ ]:
import numpy as np

x = np.array([[2,6,90,1,4,8],[56,2,11,67,90,22]])

x = np.sort(x,axis = 1)  #column wise sorting

print(x)

[[ 1  2  4  6  8 90]
 [ 2 11 22 56 67 90]]


In [ ]:
import numpy as np

x = np.array([[2,6,90,1,4,8],[56,2,11,67,90,22]])

x = np.sort(x,axis = 0)  #row wise sorting

print(x)

[[ 2  2 11  1  4  8]
 [56  6 90 67 90 22]]


**3D SORTING**

In [ ]:
import numpy as np

s = np.array([[[12,34,55,1,67],[3,678,90,24,4]],[[122,27,90,45,3],[89,33,77,25,890]]])

s = np.sort(s,axis = 0)

print(s)

[[[ 12  27  55   1   3]
  [  3  33  77  24   4]]

 [[122  34  90  45  67]
  [ 89 678  90  25 890]]]


In [ ]:
import numpy as np

s = np.array([[[12,34,55,1,67],[3,678,90,24,4]],[[122,27,90,45,3],[89,33,77,25,890]]])

s = np.sort(s,axis = 1)

print(s)

[[[  3  34  55   1   4]
  [ 12 678  90  24  67]]

 [[ 89  27  77  25   3]
  [122  33  90  45 890]]]


**COPY AND VIEW**

In [ ]:
import numpy as np
x = np.array([12,13,14,15,16,17])
y = x
z = x.copy()        #deep copy,not chage the values of the array
w = x.view()        #shallow copy,change values of the array

print(x)
print(y)
print(w)
print(z)


x[2] =209

print(x)
print(y)
print(w)
print(z)



[12 13 14 15 16 17]
[12 13 14 15 16 17]
[12 13 14 15 16 17]
[12 13 14 15 16 17]
[ 12  13 209  15  16  17]
[ 12  13 209  15  16  17]
[ 12  13 209  15  16  17]
[12 13 14 15 16 17]


**RESIZE , RESHAPE , FLATTEN**

In [ ]:
# reshape

import numpy as np

a = np.arange(16)

print(a)

print(a.shape)

b = a.reshape(2,8)

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
c = a.reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
z = a.reshape(4,5)
print(z)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
s = a.resize(4,5)
print(s)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
# resize

import numpy as np

a = np.arange(16)

print(a)

print(a.shape)

b = a.resize(4,10)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [ ]:
#flatten

import numpy as np

f = np.array([[44,55,66],[77,88,99]])

print(f)

h = f.flatten()

print(h)

[[44 55 66]
 [77 88 99]]
[44 55 66 77 88 99]


**DOT PRODUCT**

In [ ]:
import numpy as np

a = np.array([[2,3,4],[5,6,7]])

b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

print('-' * 30)

print(b)

print('-' * 30)

print(np.dot(a,b))



[[2 3 4]
 [5 6 7]]
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[ 42  51  60]
 [ 78  96 114]]


In [ ]:
# 3D DOT PRODUCT

import numpy as np

a = np.array([[[2,3,4],[2,4,2]],[[2,3,4],[2,4,2]]])

b = np.array([[[2,3,4],[2,4,2],[4,2,4]],[[2,3,4],[2,4,2],[4,2,4]]])

print(a)

print('-' * 30)

print(b)

print('-' * 30)

print(np.dot(a,b))

[[[2 3 4]
  [2 4 2]]

 [[2 3 4]
  [2 4 2]]]
------------------------------
[[[2 3 4]
  [2 4 2]
  [4 2 4]]

 [[2 3 4]
  [2 4 2]
  [4 2 4]]]
------------------------------
[[[[26 26 30]
   [26 26 30]]

  [[20 26 24]
   [20 26 24]]]


 [[[26 26 30]
   [26 26 30]]

  [[20 26 24]
   [20 26 24]]]]


In [ ]:
#layerwise minimum

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.min(a))

print(np.min(a,axis = 0))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
2
[[5 6 3]
 [4 5 2]]


In [ ]:
#columnwise minimum

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.min(a))

print(np.min(a,axis = 1))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
2
[[4 5 3]
 [5 6 2]]


In [ ]:
#rowwise minimum

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.min(a))

print(np.min(a,axis = 2))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
2
[[3 4]
 [5 2]]


In [ ]:
#layer wise maximum

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.max(a))

print(np.max(a,axis = 0))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
9
[[9 8 7]
 [8 9 6]]


In [ ]:
#column wise maximum


import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.max(a))

print(np.max(a,axis = 1))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
9
[[9 8 6]
 [8 9 7]]


In [ ]:
#row wise maximum


import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.max(a))

print(np.max(a,axis = 2))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
9
[[9 6]
 [7 9]]


In [ ]:
#layerwise median

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.median(a))

print(np.median(a,axis = 0))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
6.0
[[7. 7. 5.]
 [6. 7. 4.]]


In [ ]:
#columnwise median

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.median(a))

print(np.median(a,axis = 1))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
6.0
[[6.5 6.5 4.5]
 [6.5 7.5 4.5]]


In [ ]:
#rowwise median

import numpy as np

a = np.array([[[9,8,3],[4,5,6]],[[5,6,7],[8,9,2]]])

print(a)

print('-' * 30)

print(np.median(a))

print(np.median(a,axis = 2))

[[[9 8 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 2]]]
------------------------------
6.0
[[8. 5.]
 [6. 8.]]


# **ARRAY JOINING**

In [1]:
#vertical stack

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.vstack((a,b))

print(c)

[[ 3  4  2]
 [ 4  5  3]
 [ 4  3  1]
 [ 5 32  0]]


In [2]:
#horizontal stack

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.hstack((a,b))

print(c)

[[ 3  4  2  4  3  1]
 [ 4  5  3  5 32  0]]


In [4]:
#column stack

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.column_stack((a,b))

print(c)

[[ 3  4  2  4  3  1]
 [ 4  5  3  5 32  0]]


In [5]:
#row stack

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.row_stack((a,b))

print(c)

[[ 3  4  2]
 [ 4  5  3]
 [ 4  3  1]
 [ 5 32  0]]


**CONCATENATE**

In [8]:
#default or rowwise

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.concatenate((a,b))

print(c)

[[ 3  4  2]
 [ 4  5  3]
 [ 4  3  1]
 [ 5 32  0]]


In [9]:
#columnwise

import numpy as np

a = np.array([[3,4,2],[4,5,3]])

b= np.array([[4,3,1],[5,32,0]])

c = np.concatenate((a,b), axis = 1)

print(c)

[[ 3  4  2  4  3  1]
 [ 4  5  3  5 32  0]]
